name: Image buid

on:
  push:
    branches:
      - 'main'
  schedule:
      - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      image-require-update: ${{ steps.check.outputs.needs-updating }}
    steps:
      - name: Docker Image Update Checker
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: pihole/pihole:latest
          image: luzfcb/pihole-dot-doh:latest
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
            linux/arm/v6
        if: ${{ github.event_name == 'schedule' }}
        env:
          DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}

  build:
    needs: check
    if: ${{ github.event_name != 'schedule' || needs.check.outputs.image-require-update == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
            linux/arm/v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Fetch latest release tag
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        id: latest-tag
        with:
          repository: pi-hole/docker-pi-hole

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
            linux/arm/v6
          push: true
          provenance: false
          tags: |
            luzfcb/pihole-dot-doh:latest
            luzfcb/pihole-dot-doh:${{ steps.latest-tag.outputs.release }}
